create table if not exists "{schema_name}".CcdVisit (
       ccdVisitId bigint,
       visitId integer,
       ccdName char(3),
       raftName char(3),
       filterName char(1),
       -- nExposures INT,
       -- ra DOUBLE,
       -- decl DOUBLE,
       -- zenithDistance FLOAT,
       -- llcx INTEGER,
       -- llcy INTEGER,
       -- ulcx INTEGER,
       -- ulcy INTEGER,
       -- urcx INTEGER,
       -- urcy INTEGER,
       -- lrcx INTEGER,
       -- lrcy INTEGER,
       -- xSize INTEGER,
       -- ySize INTEGER,
       obsStart timestamp,
       expMidpt double precision,
       expTime double precision,
       -- darkTime DOUBLE,
       -- ccdTemp FLOAT,
       -- binX INTEGER,
       -- binY INTEGER,
       -- WCS BLOB,
       -- zeroPoint FLOAT,
       -- seeing FLOAT,
       -- skyBg FLOAT,
       -- skyNoise FLOAT,
       -- flags INTEGER,
       -- project CHAR(30),
       primary key (ccdVisitId)
       )
